#define IDEN    1
#define MAS     2
#define MENOS   3
#define POR     4
#define DIV     5
#define PYC     6
#define PARI    7   
#define PARD    8
#define IGUAL   9
#define ENTERO  10    
#define PRINT   11
#define STRING  12
#define COMA    13
#define LLAVEI  14
#define LLAVED  15
#define VOID    16
#define VAR     17
#define CONST   18
#define IF      19
#define ELSE    20
#define WHILE   21
#define READ    22
